server:
  port: 8090

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        processBook-in-0:
          destination: create-book
        processBook-out-0:
          destination: store-book
  application:
    name: check-book-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true