spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

server:
  port: 0