spring:
  application:
    name: eureka-client

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-service-url-poll-interval-seconds: 35
  instance:
    prefer-ip-address: true

server:
  port: 0