server:
  port: 8093

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        getBook-in-0:
          destination: store-book
  application:
    name: store-book-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true