server:
  port: 8091

spring:
  cloud:
    stream:
      kafka:
        binder:
          auto-add-partitions: true
      bindings:
        sendBook-out-0:
          destination: create-book
  application:
    name: creation-book-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true