spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  profiles:
    active: native
  data:
    mongodb:
      database: mongodb
  sleuth:
    sampler:
      probability: 2.0
  zipkin:
    enabled: true

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true