spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaximShaternikov/eureka-config.git
          search-paths: "ms-config-properties/{application}/{profile}"
          clone-on-start: true
          default-label: main

server:
  port: 8888

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true